### ISSUE TITLE
Stream limits

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-webtrans/draft-webtransport-http2#24]
This is likely shared with the HTTP/3 mapping also, but I'm here first.

Web applications will want some degree of certainty about the streams they are able to access.  As they also operate servers, this is probably not so bad in the client-to-server direction.  The main concern for client-to-server is the potential for the connection to be used for HTTP requests that consume these limits.  In the server-to-client direction clients might need to provide some number of streams that it would guarantee that a server can use for a given session.

As multiple sessions are involved, this gets harder, because the web security model might prevent us from exposing information about what other origins are using a shared connection for.  That said, it's not clear that there is any value in withholding this information either (see #23) as the security boundary is essentially already gone once coalescing is involved.

(I'm deliberately not considering isolation of state by top-level browsing context; I expect that no coalescing or connection sharing would occur for different top-level sites.)

**Comment by ekinnear** [comment]
We may want to move this over to WT over HTTP/3 now, since post-#26 we're keeping everything within the CONNECT stream. It becomes an issue again if people "break out" WT streams onto native HTTP/2 streams, like WT over HTTP/3 does.

**Comment by martinthomson** [comment]
Sounds like a plan.

**Comment by ekinnear** [comment]
Moved to H3, closing here
