### ISSUE TITLE
Use datagram CAPSULE?

### ISSUE THREAD

**Issue by afrind** [ietf-wg-webtrans/draft-webtransport-http2#25]
If the CAPSULE frame defined in the HTTP/3 DATAGRAM draft is extended to HTTP/2, then it probably makes more sense to use that, rather than a new WT_DATAGRAM frame.

**Comment by ekinnear** [comment]
Agreed, if this comes to HTTP/2 then reusing it seems better than minting yet-another-of-the-same thing.

**Comment by ekinnear** [comment]
We need to decide whether or not we're using capsules, and if so, how do we shape it.

**Comment by DavidSchinazi** [comment]
Chair notes from IETF 112 meeting: this is on hold pending output of MASQUE HTTP Datagrams design team

**Comment by DavidSchinazi** [comment]
Chair: discussed at 113, design team will be formed to discuss this issue, led by @ekinnear. The chairs will email a call for volunteers on the mailing list

**Comment by ekinnear** [comment]
Design team output presented at IETF 114, further updates coming for 115.
