### ISSUE TITLE
Potentially remove Final Size

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-webtrans/draft-webtransport-http2#29]
This field isn't necessary because of the in-order, reliable delivery of the underlying transport.  That said, I'm not opposed to leaving it here for symmetry with QUIC.  We could also say - it's unused, or what to do if this value is different from the value computed as the size of sent data on this stream?

_Originally posted by @afrind in https://github.com/ietf-wg-webtrans/draft-webtransport-http2/pull/26#discussion_r736004658_

**Comment by afrind** [comment]
> The frame format is not identical to QUIC as you have added lengths to all of the frames. This is a good choice, I think, but it means that you don't have an identical parser. 

Should we make the length be first in every frame so we can strip it and use the same parser?

**Comment by martinthomson** [comment]
That is an interesting suggestion. It is even ... Sort of ... Consistent with HTTP/2.

**Comment by afrind** [comment]
I guess WebTransport frames are explicitly not capsules, but they are the same as capsules, I think?  Capsules are explicitly "TLV".

**Comment by ekinnear** [comment]
Yeah, I'm expecting we'll have a slide at 112 about the lengths. QUIC has them for the frames where you have something that varies in length, and I put it in every frame here. Seems like the best choices are either (a) decide that was unnecessary and take them out or (b) move them to the front to make it easier. We also need to see if it would be a capsule or not.

Seems like for this issue, we need to decide whether or not we're okay keeping "useless" fields solely for the sake of looking like QUIC. If so, moving length to the front and then keeping the rest of the frame identical seems great. If not, then out with the extra and the position of length doesn't matter nearly as much.

Will raise at 112 so we can settle on "useless" fields.

**Comment by afrind** [comment]
Do we think that WT over H2 should be using Capsules?  In particular it might seem silly to have two different ways to send a DATAGRAM.  If we think that all WT Frames should be capsules, and we want length up front, we need to take that up in MASQUE.

Besides Final Offset, are there any other "useless" fields?

**Comment by DavidSchinazi** [comment]
Chair notes from IETF 112 meeting: this is on hold pending #25 which is itself on hold pending output of MASQUE HTTP Datagrams design team

**Comment by ekinnear** [comment]
Also from 112: No strong desire to keep things exactly aligned with QUIC frames, so fine to have length in any position and to remove final length.
