### ISSUE TITLE
Why forbid frames before the session is accepted?

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-webtrans/draft-webtransport-http2#38]
>  From the client's perspective, a WebTransport session is established when the client receives a 200 response. From the server's perspective, a session is established once it sends a 200 response. Both endpoints MUST NOT send any WebTransport frames on a given session before that session is established.

I don't think that this is necessary, or helpful.  And I don't think that you can police it either.

It is true that a client cannot initiate any streams before the session is created (because the stream limits start at zero), but I see no reason not to pipeline WT_DATAGRAM or MAX_* frames if the h2-level flow control permits it.  The MAX_* frames are particularly useful in that they allow the server to send real data immediately, cutting a round trip off.

**Comment by ekinnear** [comment]
Given that the limits start at zero (do we state that explicitly anywhere?), and we're not including any sort of SETTINGS/default settings, it definitely seems like we ought to be able to just start spewing frames into the CONNECT stream, which are discarded if the CONNECT request is rejected.

**Comment by DavidSchinazi** [comment]
Chair: discussed at 113, consensus in room to allow sending any frames allowed by flow control

**Comment by ekinnear** [comment]
Text in H3 here: https://github.com/ietf-wg-webtrans/draft-ietf-webtrans-http3/pull/80, can probably make it look similar for H2.
