### ISSUE TITLE
WT_PADDING is redundant with h2 padding

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-webtrans/draft-webtransport-http2#40]
This is not a bad thing.  In fact it's a deliberate choice.  It might be worth noting the redundancy so people don't think we're a bit dim.  We might also add that this padding is less tunable than h2 padding.

**Comment by vasilvv** [comment]
Do we actually need WT_PADDING, and if so, does it need to be in this document?

**Comment by DavidSchinazi** [comment]
@martinthomson do you remember why we deliberately chose to have this separate padding instead of just relying on the h2 padding?

**Comment by martinthomson** [comment]
I don't recall the specifics 18 months on.  However, the basic problems are invariant.  The different padding schemes offer different capabilities due to a bunch of different design trade-offs and inherent properties of each approach.

h2 padding only applies to one hop, but WT_PADDING would traverse intermediaries (because it is application data as far as they are concerned).  Consequently, you might want to use WT_PADDING if your goal is to protect against leaks on remote hops.  This is because each operates on a different scope.

WT_PADDING doesn't get to be smaller than the minimum capsule size, but h2 padding can be any size.  That means that a padding strategy is potentially more efficient in h2 as you need to include WT_PADDING and its overheads.  This is because the more padding integration in h2 is more complete, but also more complex.

Finally, there are all the usual software engineering constraints.  Maybe you have access to padding functions in your WT stack, but not the h2 stack.

**Comment by ekinnear** [comment]
Many thanks @martinthomson! Added a version of that to the padding section (noting that padding is a generic capsule being defined here, so others can use it even if not over HTTP/2).
