### ISSUE TITLE
Transport Properties (currently Section 8)

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-webtrans/draft-webtransport-http2#48]
When I did #39, I hadn't read Section 8.  My suggestion is that this be merged into the material from the (current) Sections 4 and 5.

Also, this is the first use of Http2Transport. I think that we should remove that.  It's a fine class name for a C++ implementation, but we don't use it elsewhere.

**Comment by ekinnear** [comment]
Just to make sure I understand, the idea is for this "what properties do we provide and how do they satisfy the WT requirements" part to be up front with 4/5? Seems good to me.

> Also, this is the first use of Http2Transport.

Yeah, that's mostly leftover from previous versions where we had a more defined name. Can clean up and not lose anything of value, I think.
