### ISSUE TITLE
The length field in the generic deffinition of frame

### ISSUE THREAD

**Issue by ddragana** [ietf-wg-webtrans/draft-webtransport-http2#52]
The generic frame definition has a length field, but that field is set to 0 for some frames, I think that field should be frame specific and not defined for all frame.

**Comment by afrind** [comment]
This is somewhat tied to the discussion in #29.  Should we exactly mirror QUIC, making it possible to re-use the parser bits?  Do we need to handle unknown frame types?  Should we be using CAPSULE protocol?

**Comment by ddragana** [comment]
I have missed previous discussions. From the today's discussion on the meeting, we can close this issue.
