### ISSUE TITLE
Section WT_RESET_STREAM frame

### ISSUE THREAD

**Issue by ddragana** [ietf-wg-webtrans/draft-webtransport-http2#53]
> After sending a WT_RESET_STREAM, an endpoint ceases transmission and
   retransmission of WT_STREAM frames on the identified stream.  A
   receiver of WT_RESET_STREAM can discard any data that it already
   received on that stream."

This is using TCP and should not talk about ceasing  retransmissions.

**Comment by ekinnear** [comment]
Very good point! Will clean up
