### ISSUE TITLE
Choose a status code for when a resource does not support WebTransport

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-webtrans/draft-webtransport-http2#61]
Current text:
>Upon receiving an extended CONNECT request with a `:protocol` field set to
`webtransport`, the HTTP server checks if the identified resource supports
WebTransport sessions. If the resource does not, the server SHOULD reply with
status code 404 ({{Section 6.5.4 of !RFC7231}}). If it does, it MAY accept the
session by replying with a 2xx series status code, as defined in Section 15.3
of {{!SEMANTICS=I-D.ietf-httpbis-semantics}}. The WebTransport server MUST
verify the `Origin` header to ensure that the specified origin is allowed to
access the server in question.

----
> We probably already talked about this, but 404 is not right. 406, maybe. 400, sure. But 404 indicates that the resource doesn’t exist and the text here implies that it does.

_Originally posted by @martinthomson in https://github.com/ietf-wg-webtrans/draft-webtransport-http2/pull/58#discussion_r1008899128_

**Comment by vasilvv** [comment]
The corresponding text in HTTP/3 appears to be:
> Upon receiving an extended CONNECT request with a :protocol field set to webtransport, the HTTP/3 server can check if it has a WebTransport server associated with the specified :authority and :path values. If it does not, it SHOULD reply with status code 404 (Section 15.5.4, [[HTTP](https://www.ietf.org/archive/id/draft-ietf-webtrans-http3-03.html#HTTP)]).

This is correct, though I am not sure how necessary it is.

**Comment by DavidSchinazi** [comment]
Discussed in editor's call: 406 sounds good
