### ISSUE TITLE
Can a client send a request body without awaiting a response?

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-webtrans/draft-webtransport-http2#62]
I don’t agree with this. A client can send a request body without awaiting a response. Always.

_Originally posted by @martinthomson in https://github.com/ietf-wg-webtrans/draft-webtransport-http2/pull/58#discussion_r1008899457_

**Comment by vasilvv** [comment]
Are those concerns orthogonal?  I don't believe there is anything in the text that says you cannot send data before the session is established.
