### ISSUE TITLE
Use HTTP status code 2xx instead of 200

### ISSUE THREAD

**Issue by DavidSchinazi** [ietf-wg-webtrans/draft-webtransport-http2#69]
The document currently mentions HTTP status code 200 explicitly, instead of following the usual convention of saying "any 2xx" status code. We already made this change in WebTransport over HTTP/3, we should do the same in this doc.

**Comment by ekinnear** [comment]
Ack, we're a bit mixed in the HTTP/2 document right now, will update so we're consistent everywhere.
